Removed context.TODO() arguments added in https://github.com/kubernetes/kubernetes/pull/87299, which makes go complain: /elasticsearch_logging_discovery.go:106:48: too many arguments in call to client.CoreV1().Namespaces().Get